# Site Settings
title:               "SM2G"
tagline:             "Amat Victoria Curam"
description:
baseurl:            #""
url:                #"https://sm2g.github.io"
github:
  url:               "https://sm2g.github.io"
author:
  name:              "Samy Gejzenblozen"
  email:             "samy.gejz@gmail.com"
  twitter:           "sm2g"
  instagram:         "sm2g"
  github:            "sm2g"
  facebook:          "samy.gejzenblozen"
  linkedin:          "samy.gejzenblozen"

navigation:
- title: About
  url: /about
- title: Blog
  url: /blog
- title: Tags
  url: /tags
- title: Tips
  url: /tips

donations:
- code: BTC
  symbol: "฿"
  public_key: "36XvwAsrA63cETKN3rHvTqyyUE7Spvof9T"
- code: ETH
  symbol: "Ξ"
  public_key: "0xf05080371075b00C6643B38aCd16De7F5948343E"

paginate:            12
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate]
