# Site settings
title: SM2G
motto: Concieve. Believe. Achieve.
email: samy.gejz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sm2g.github.io" # the base hostname & protocol for your site
twitter_username: sm2g
github_username:  sm2g

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jemoji

google_analytics: 
show_downloads: true
theme: jekyll-theme-tactile