# Site Settings
title:               Samy Gejzenblozen
tagline:             Data Engineer
description:
baseurl:            "/site"
url:                "https://sm2g.github.io"
github:
  url:              "https://sm2g.github.io/site"
author:
  name:              "Samy Gejzenblozen"
  email:             "samy.gejz@gmail.com"
  twitter:           "sm2g"
  instagram:         "sm2g"
  github:            "sm2g"
  facebook:          "samy.gejzenblozen"
  linkedin:          "samy.gejzenblozen"
navigation:
- title: About
  url: /about
- title: Blog
  url: /blog
- title: Contact
  url: /contact

paginate:            5
#disqus:              #"disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]


# Site Settings
title:               Lagrange
tagline:             a minimalist Jekyll theme
