# Site Settings
title:               "Samy Gejzenblozen"
tagline:             "Data Engineer"
description:
baseurl:            #""
url:                #"https://sm2g.github.io"
github:
  url:               #"https://sm2g.github.io"
author:
  name:              "Samy Gejzenblozen"
  email:             "samy.gejz@gmail.com"
  twitter:           "sm2g"
  instagram:         "sm2g"
  github:            "sm2g"
  facebook:          "samy.gejzenblozen"
  linkedin:          "samy.gejzenblozen"
navigation:
- title: Blog
  url: /blog
- title: Contact
  url: /contact
- title: About
  url: /about

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
