# Site settings
title: Work in progress
email: samy.gejz@gmail.com
#url: https://sm2g.github.io
url: http://localhost:4000
description: "News from the front"
#description: "It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Footer settings
footer: SM2G

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/sm2g
  - title: twitter
    url: https://twitter.com/SM2G

# Build settings
markdown: kramdown
permalink: pretty
encoding: utf-8
paginate: 10

gems: [jekyll-paginate]
